# Generated by Django 4.0.5 on 2022-06-18 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250, verbose_name='პროფესია')),
                ('linkedin_address', models.CharField(max_length=255, validators=[teacher.models.validate_linkedin_address])),
                ('bio', models.TextField(verbose_name='ბიოგრაფია')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ინსტრუქტორი',
            },
        ),
    ]
