# Generated by Django 4.0.5 on 2022-06-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='სათაური')),
                ('about_course', models.TextField(verbose_name='კურსის შესახებ')),
                ('language', models.CharField(max_length=90, verbose_name='ენა')),
                ('requirement', models.TextField(verbose_name='მოთხოვნები')),
                ('buyer', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='მყიდველი')),
                ('created_by', models.ManyToManyField(to='teacher.teacher', verbose_name='ინსტრუქტორი')),
            ],
            options={
                'verbose_name': 'კურსი',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='შეფასება')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='კურსი')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='შემფასებელი')),
            ],
            options={
                'verbose_name': 'შეფასება',
            },
        ),
    ]
